### PR TITLE
Update github.com/weaveworks/common & dependencies (needs go1.8)

### PR DESCRIPTION
**Pull request by rndstr**
introduces weaveworks/common#42

----
Bumped all packages that make the build fail:

    gvt update github.com/golang/protobuf/proto
    gvt fetch github.com/golang/protobuf/ptypes
    gvt fetch google.golang.org/genproto/googleapis/rpc/status
    gvt update google.golang.org/grpc/status
    gvt update google.golang.org/grpc/transport
    gvt update golang.org/x/net/http2

Latest weaveworks/common only compiles on go1.8, scope uses go1.7 right now.

### CODE REVIEW

**Comment by bboreham** [comment]
Failing in CI with `vendor/github.com/weaveworks/common/middleware/path_rewrite.go:28: undefined: url.PathUnescape`

**Comment by rndstr** [comment]
rebased master (with go1.8)

**Comment by 2opremio** [comment]
@rndstr ping
