### ISSUE TITLE
Scope stuck "connecting to scope"

### ISSUE THREAD

**Issue by tomwilkie** [weaveworks/scope#2154]
With this in the console:
```
VM245 vendors-b764d66….js?6ded3cd…:12 Uncaught TypeError: t.filter is not a function
    at f (VM245 vendors-b764d66….js?6ded3cd…:12)
    at i (VM245 vendors-b764d66….js?6ded3cd…:33)
    at f (VM245 vendors-b764d66….js?6ded3cd…:33)
    at l (VM245 vendors-b764d66….js?6ded3cd…:33)
    at VM245 vendors-b764d66….js?6ded3cd…:33
    at dispatch (VM245 vendors-b764d66….js?6ded3cd…:45)
    at VM245 vendors-b764d66….js?6ded3cd…:1
    at VM245 vendors-b764d66….js?6ded3cd…:33
    at Object.success (VM245 vendors-b764d66….js?6ded3cd…:13)
    at Reqwest.o.success._successHandler (VM245 vendors-b764d66….js?6ded3cd…:50)
```

**Comment by davkal** [comment]
Looks like requests to the backend are malformed when used in the service UI: `http://hostname/api/api/app/{org}/api/topology`

Notice the double `api` in the beginning.

Possible introduced by #2144

**Comment by 2opremio** [comment]
This happened somewhere between 244bba2 and 29edaeb . I doubt this was the backend. My main suspect is https://github.com/weaveworks/scope/pull/2144

@foot @davkal @jpellizzari @fbarl This is urgent, it broke dev (and then prod)

**Comment by 2opremio** [comment]
Interestingly, I did test prod right after the upgrade and Scope was working. Could it be due to caching of the assets?

**Comment by davkal** [comment]
> Interestingly, I did test prod right after the upgrade and Scope was working. Could it be due to caching of the assets?

That could have been masking the issue.

**Comment by 2opremio** [comment]
So, IMO, we need to do three things to prevent this from happening in the future:

1. Fix the assets caching problem (if there´s any, I believe there is)
2. Add an integration test minimally testing the UI
3. Be more thorough when testing changes

**Comment by 2opremio** [comment]
But let´s of course first figure out what the problem is.

**Comment by rade** [comment]
I thought we had some metrics/alerts for set up to catch this sort of breakage.

**Comment by 2opremio** [comment]
> I thought we had some metrics/alerts for set up to catch this sort of breakage.
Assuming the problem comes from the UI, I don´t think so.

**Comment by davkal** [comment]
We have monitoring in place, see https://github.com/weaveworks/monitoring/issues/101
but no alerting yet.

**Comment by rade** [comment]
> weaveworks/monitoring/issues/101

exactly.

> but no alerting yet.

Understood, but did this problem at least show up in the data?

**Comment by jpellizzari** [comment]
@rade This was neither a page-load or page-render error. The app was served successfully and the requested page was rendered. This is the result of a bad URL path resulting in index.html being served to a call that expects JSON. Our HTTP library decided it was a string and passed it to a .filter() call.

**Comment by 2opremio** [comment]
>  This is the result of a bad URL path

Did you track down how the bad URL was generated?

**Comment by jpellizzari** [comment]
@2opremio Yes, it is a result of #2144. I added some extra logic so that scope will get the right URL path while running as a component, as well as an iFrame. There is one commit I was expecting to see on master that isn't there, so it's likely I forgot to push it before merging my PR.

**Comment by jpellizzari** [comment]
This was the commit I was referring to that never got pushed:

https://github.com/weaveworks/scope/commit/8ea7de9721630e071079f74acebb90c88798d2e3

**Comment by jpellizzari** [comment]
Fixed in #2159

**Comment by 2opremio** [comment]
`https://cloud.weave.works/demo/` is still broken after the fix. See:

<img width="1660" alt="screen shot 2017-01-30 at 11 45 25" src="https://cloud.githubusercontent.com/assets/2362916/22420261/e045acc2-e6e1-11e6-8b9b-51a5d38455b6.png">

Note how the url is wrong: https://cloud.weave.works/api/demo/api

**Comment by 2opremio** [comment]
I reverted prod to 244bba2 but it's still reproducible at http://frontend.dev.weave.works/demo/

**Comment by davkal** [comment]
@jpellizzari to debug this, you can simply run `npm start` and then access http://localhost:4043/scoped/
This was specifically included in the express server to test path prefixes. (But maybe that should have been automated.)

At first glance it looks like this heuristic caused the problem:
```js
const isStandalone = window.location.pathname === '/' || /\/(.+).html/.test(window.location.pathname);
```

Maybe better to detect the opposite (scope-as-component)?

**Comment by 2opremio** [comment]
@awh discovered we are having the same (or similar problem) at `/admin/scope` in Weave Cloud. This is not covered by @davkal's hotfix.

For instance, at http://frontend.dev.weave.works/admin/scope/ I get:

```
Uncaught TypeError: t.filter is not a function
    at f (vendors-58f07ad….js?547653e…:12)
    at i (vendors-58f07ad….js?547653e…:33)
    at f (vendors-58f07ad….js?547653e…:33)
    at l (vendors-58f07ad….js?547653e…:33)
    at vendors-58f07ad….js?547653e…:33
    at dispatch (vendors-58f07ad….js?547653e…:45)
    at vendors-58f07ad….js?547653e…:1
    at vendors-58f07ad….js?547653e…:33
    at dispatch (vendors-58f07ad….js?547653e…:45)
    at Object.success (vendors-58f07ad….js?547653e…:13)
```

<img width="1507" alt="screen shot 2017-02-02 at 15 51 22" src="https://cloud.githubusercontent.com/assets/2362916/22554257/bd4c8c92-e95f-11e6-9efa-026bf209214b.png">

**Comment by 2opremio** [comment]
It's the same problem (the UI is requesting `http://frontend.dev.weave.works/api/admin/scope/api`)

**Comment by jpellizzari** [comment]
#2202 Has been merged and pushed to dev and is working correctly.

**Comment by ngehani** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Cluster Health](https://trello.com/c/1oZ7eFPB/124-cluster-health)
